sudo: required
services:
    - docker

before_install:
    - docker build -t bmota/react-test -f ./client/Dockerfile.dev .
script:
    - docker run -e CI=true bmota/react-test npm test

after_success:
    - docker build -t bmota/multi-client ./client .
    - docker build -t bmota/multi-nginx ./nginx .
    - docker build -t bmota/multi-server ./server .
    - docker build -t bmota/multi-worker ./worker .
    # Log in to the docker CLI
    - echo  "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
    - docker push bmota/multi-client 
    - docker push bmota/multi-nginx 
    - docker push bmota/multi-server 
    - docker push bmota/multi-worker 




